# Generated by Django 5.0.6 on 2024-06-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointBank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
