# Generated by Django 5.0.6 on 2024-06-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointBank', '0003_user_email_alter_user_login_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('_from', models.TextField()),
                ('_to', models.TextField()),
            ],
        ),
    ]
