# Generated by Django 5.0.6 on 2024-06-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointBank', '0004_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
