# Generated by Django 5.0.6 on 2024-06-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointBank', '0007_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='pointBank.ticket'),
        ),
    ]
