# Generated by Django 5.0.6 on 2024-06-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointBank', '0008_user_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.JSONField(),
        ),
    ]
