# Generated by Django 5.0.6 on 2024-06-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointBank', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isEmailConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
