# Generated by Django 5.0.6 on 2024-06-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointBank', '0010_user_isemailconfirmed_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastCode',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
