# Generated by Django 5.0.6 on 2024-06-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointBank', '0011_user_lastcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastCode',
            field=models.IntegerField(blank=True, max_length=4),
        ),
    ]
