# Generated by Django 5.0.6 on 2024-06-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointBank', '0012_alter_user_lastcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastCode',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
